on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: windows-latest
    env:
      Configuration: Release
  
    steps:
      - uses: actions/checkout@v3

      - name: Import build script
        run: Import-Module .\Build.ps1

      - name: Test
        run: Test-PoshSvn

      - name: Publish
        run: Build-PoshSvn

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: PoshSvn
          path: .\publish.zip
