name: Build and Test PoshSvn

on:
  push:
    branches: ["*"]
    paths-ignore:
      - 'www/**'
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-poshsvn:
    runs-on: windows-latest

    strategy:
      matrix:
        platform:
        - x64
        - x86

    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
      MSBuildCommonParameters: /property:Configuration=Release /property:Platform=${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
              core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
              core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - uses: actions/checkout@v4

      - name: Restore
        run: MSBuild.exe /target:restore ${{ env.MSBuildCommonParameters }}

      - name: vcpkg
        run: MSBuild.exe /target:vcpkg ${{ env.MSBuildCommonParameters }}

      - name: Build
        run: MSBuild.exe /target:build ${{ env.MSBuildCommonParameters }}

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: PoshSvn-${{ matrix.platform }}
          path: .\bin\poshsvn

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release-${{ matrix.platform }}
          path: .\bin\Release-${{ matrix.platform }}

      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1.2

      - name: Test PoshSvn
        run: vstest.console.exe .\bin\Release-${{ matrix.platform }}\PoshSvn.Tests.dll

      - name: Test PoshSvn.Common
        run: vstest.console.exe .\bin\Release-${{ matrix.platform }}\PoshSvn.Common.Tests.dll
