name: Publish

on:
  release:
    types: published

permissions: write-all

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - uses: robinraju/release-downloader@v1.9
        with:
          fileName: "poshsvn.zip"
          tag: ${{ github.ref_name }}
