name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions: write-all

jobs:
  create-release:
    runs-on: windows-latest

    steps:
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false

    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
      release_id: ${{ steps.create-release.outputs.id }}

  build-poshsvn:
    needs:
      - create-release

    runs-on: windows-latest

    environment: release

    strategy:
      matrix:
        platform:
        - x64
        - x86

    env:
      MSBuildCommonParameters: /property:Configuration=Release /property:Platform=${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
  
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - uses: actions/checkout@v4

      # Build
      - name: Build
        run: ./build.ps1

      - name: Sign Installer
        uses: azure/trusted-signing-action@v0.5.1
        with:
          endpoint: https://eus.codesigning.azure.net/
          trusted-signing-account-name: ${{ secrets.AZURE_TRUSTED_SIGNING_ACCOUNT_NAME }}
          certificate-profile-name: ${{ secrets.AZURE_CERTIFICATE_PROFILE_NAME }}
          files: |
            .\bin\Release-${{ matrix.platform }}\Installer\en-US\PoshSvn-${{ github.ref_name }}-${{ matrix.platform }}.msi
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256

      # Release
      - name: Upload package to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: .\bin\Release-${{ matrix.platform }}\PoshSvn.zip
          asset_name: PoshSvn-${{ github.ref_name }}-${{ matrix.platform }}.zip
          asset_content_type: application/zip

      - name: Upload installer to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: .\bin\Release-${{ matrix.platform }}\Installer\en-US\PoshSvn-${{ github.ref_name }}-${{ matrix.platform }}.msi
          asset_name: PoshSvn-${{ github.ref_name }}-${{ matrix.platform }}.msi
          asset_content_type: application/msi

      # Artifacts
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release-${{ matrix.platform }}
          path: .\bin\Release-${{ matrix.platform }}
  
      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1.2

      - name: Test PoshSvn
        run: vstest.console.exe .\bin\Release-${{ matrix.platform }}\PoshSvn.Tests.dll

      - name: Test PoshSvn.Common
        run: vstest.console.exe .\bin\Release-${{ matrix.platform }}\PoshSvn.Common.Tests.dll

  publish-powershellgallery:
    runs-on: windows-latest
    needs:
      - build-poshsvn
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Release-x64
          path: .\bin\Release-x64
      - name: Publish package to PowerShell gallery
        run: Publish-Module -Path .\bin\Release-x64\PoshSvn -NuGetApiKey ${{ secrets.PS_GALLERY_TOKEN }}

  publish-vscode-extension:
    runs-on: windows-latest
    needs:
      - build-poshsvn
      - create-release
    steps:
      - name: Download Release artifact
        uses: actions/download-artifact@v4
        with:
          name: Release-x64
          path: .\bin\Release-x64
      - name: Install vsce
        run: npm install -g @vscode/vsce
      - name: Publish
        run: vsce publish --pat ${{ secrets.VSCODE_STORE_TOKEN }}
        working-directory: .\bin\Release-x64\PoshSvn.VSCode
      # - name: Upload package to release
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ needs.create-release.outputs.upload_url }}
      #     asset_path: .\bin\Release-x64\PoshSvn.VSCode.vsix
      #     asset_name: PoshSvn.VSCode.vsix
      #     asset_content_type: application/vsix

  publish-release:
    needs:
      - build-poshsvn
      - create-release
      - publish-vscode-extension
    runs-on: windows-latest
    steps:
      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.create-release.outputs.release_id }}
