name: Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions: write-all

jobs:
  create_release:
    runs-on: windows-latest

    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: true
        prerelease: false

    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      release_id: ${{ steps.create_release.outputs.id }}

  build-poshsvn:
    needs: create_release

    runs-on: windows-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build
      run: MSBuild.exe /restore /target:build /property:Configuration=Release /property:Platform=x64

    - name: Upload package to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: .\bin\poshsvn.zip
        asset_name: poshsvn.zip
        asset_content_type: application/zip

    - name: Upload installer to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: .\bin\Release\PoshSvn.msi
        asset_name: PoshSvn.msi
        asset_content_type: application/msi

    - name: Upload VSCode extension package to release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_path: .\bin\Release\PoshSvn.VSCode.vsix
        asset_name: PoshSvn.VSCode.vsix
        asset_content_type: application/vsix

    - name: Publish package to PowerShell gallery
      run: Publish-Module -Path ".\bin\poshsvn" -NuGetApiKey ${{ secrets.PS_GALLERY_TOKEN }}

    - name: Publish VSCode extension
      run: vsce publish --packagePath .\bin\Release\PoshSvn.VSCode.vsix --pat ${{ secrets.VSCODE_STORE_TOKEN }}

  publish_release:
    needs: 
      - build-poshsvn
      - create_release

    runs-on: windows-latest

    steps:
      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ needs.create_release.outputs.release_id }}