name: Update wiki

on:
  push:
    branches:
    - trunk
    paths:
    - PoshSvn.Docs/en-US/**
    - .github/workflows/update-wiki.yml
  workflow_dispatch:

jobs:
  update-wiki:
    runs-on: windows-latest
    steps:
      - name: Checkout PoshSvn
        uses: actions/checkout@v4
        with:
          path: poshsvn

      - name: Checkout PoshSvn wiki 
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          path: poshsvn.wiki

      - name: Cleanup wiki directory
        run: Remove-Item .\poshsvn.wiki\* -Recurse

      - name: Copy new docs pages
        run: Copy-Item .\poshsvn\PoshSvn.Docs\en-US\* -Recurse .\poshsvn.wiki\

      - name: Check status
        id: check_status
        working-directory: poshsvn.wiki
        run: |
          if (git status --porcelain) {
            Write-Output "has_changed=true" >> $GITHUB_OUTPUT
          }

      - name: Setup name
        if: steps.check_status.outputs.has_changed == 'true'
        run: git config user.name "github-actions[bot]"
        working-directory: poshsvn.wiki

      - name: Setup email
        if: steps.check_status.outputs.has_changed == 'true'
        run: git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        working-directory: poshsvn.wiki

      - name: Add new files
        if: steps.check_status.outputs.has_changed == 'true'
        run: git add .
        working-directory: poshsvn.wiki

      - name: Git Commit
        if: steps.check_status.outputs.has_changed == 'true'
        run: git commit -m "[automatic] Update wikis for commit ${{ github.sha }}"
        working-directory: poshsvn.wiki
        continue-on-error: true

      - name: Git Push
        if: steps.check_status.outputs.has_changed == 'true'
        run: git push
        working-directory: poshsvn.wiki
